import type {Lang} from "./types";
export const languages:{code:Lang;label:string}[]=[{code:"el",label:"🇬🇷 Ελληνικά"},{code:"en",label:"🇬🇧 English"},{code:"de",label:"🇩🇪 Deutsch"},{code:"fr",label:"🇫🇷 Français"},{code:"it",label:"🇮🇹 Italiano"},{code:"es",label:"🇪🇸 Español"}];
const en={subtitle:"AI-assisted automotive diagnostics",vehicle:"Vehicle details",diagnosis:"Diagnosis",make:"Make",model:"Model",year:"Year",engine:"Engine",fuel:"Fuel",mileage:"Mileage",dtc:"DTC trouble code",symptom:"Symptom description",diagnose:"Analyze fault",analyzing:"Analyzing...",summary:"Summary",causes:"Likely causes",checks:"Priority checks",measurements:"Measurements / tests",repair:"Suggested repair path",warnings:"Warnings",confidence:"Confidence",empty:"Enter a DTC or describe the symptom.",error:"Diagnosis failed. Please try again.",disclaimer:"Diagnostic aid only. Confirm conclusions with real measurements and manufacturer specifications."};
export const t={
el:{subtitle:"Έξυπνη διάγνωση αυτοκινήτου με AI",vehicle:"Στοιχεία οχήματος",diagnosis:"Διάγνωση",make:"Μάρκα",model:"Μοντέλο",year:"Έτος",engine:"Κινητήρας",fuel:"Καύσιμο",mileage:"Χιλιόμετρα",dtc:"Κωδικός βλάβης DTC",symptom:"Περιγραφή συμπτώματος",diagnose:"Ανάλυση βλάβης",analyzing:"Ανάλυση...",summary:"Σύνοψη",causes:"Πιθανές αιτίες",checks:"Έλεγχοι προτεραιότητας",measurements:"Μετρήσεις / δοκιμές",repair:"Προτεινόμενη πορεία επισκευής",warnings:"Προσοχή",confidence:"Βεβαιότητα",empty:"Βάλε έναν κωδικό DTC ή περιέγραψε το σύμπτωμα.",error:"Η διάγνωση δεν ολοκληρώθηκε. Δοκίμασε ξανά.",disclaimer:"Βοηθητικό διαγνωστικό εργαλείο. Επιβεβαίωσε κάθε συμπέρασμα με πραγματικές μετρήσεις και εργοστασιακές προδιαγραφές."},
en,
de:{...en,subtitle:"KI-gestützte Fahrzeugdiagnose",vehicle:"Fahrzeugdaten",diagnosis:"Diagnose",make:"Marke",model:"Modell",year:"Baujahr",engine:"Motor",fuel:"Kraftstoff",mileage:"Kilometerstand",dtc:"DTC-Fehlercode",symptom:"Symptombeschreibung",diagnose:"Fehler analysieren"},
fr:{...en,subtitle:"Diagnostic automobile assisté par IA",vehicle:"Informations véhicule",diagnosis:"Diagnostic",make:"Marque",model:"Modèle",year:"Année",engine:"Moteur",fuel:"Carburant",mileage:"Kilométrage",dtc:"Code défaut DTC",symptom:"Description du symptôme",diagnose:"Analyser la panne"},
it:{...en,subtitle:"Diagnosi automobilistica assistita da IA",vehicle:"Dati veicolo",diagnosis:"Diagnosi",make:"Marca",model:"Modello",year:"Anno",engine:"Motore",fuel:"Carburante",mileage:"Chilometraggio",dtc:"Codice DTC",symptom:"Descrizione sintomo",diagnose:"Analizza guasto"},
es:{...en,subtitle:"Diagnóstico automotriz asistido por IA",vehicle:"Datos del vehículo",diagnosis:"Diagnóstico",make:"Marca",model:"Modelo",year:"Año",engine:"Motor",fuel:"Combustible",mileage:"Kilometraje",dtc:"Código DTC",symptom:"Descripción del síntoma",diagnose:"Analizar avería"}}
